name: marvel
description: Marvel Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # Networking
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.5.0
  retrofit: ^3.0.1+1
  built_value: ^8.2.3
  dio_logging_interceptor: ^1.0.1
  dio: ^4.0.6
  # Caching
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  
  equatable: ^2.0.3
  google_fonts: ^2.3.2
  
dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  built_value_generator: ^8.2.3
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.2
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  retrofit_generator: ^3.0.1+1

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/images/
  fonts:
      - family: Marvel
        fonts:
          - asset: assets/fonts/marvel.otf
        